openapi: 3.1.0
info:
  title: Sample Vercel API
  version: 1.0.0
servers:
  - url: 'http://localhost:80'
paths:
  /api/v1/health:
    get:
      description: ヘルスチェック
      responses:
        204:
          description: 204 response
