// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

// DeleteUserResponse defines model for DeleteUserResponse.
type DeleteUserResponse struct {
	User *User `json:"user,omitempty"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	User *User `json:"user,omitempty"`
}

// PatchUserRequest defines model for PatchUserRequest.
type PatchUserRequest struct {
	Name string `json:"name"`
}

// PatchUserResponse defines model for PatchUserResponse.
type PatchUserResponse struct {
	User *User `json:"user,omitempty"`
}

// PostUserRequest defines model for PostUserRequest.
type PostUserRequest struct {
	Name string `json:"name"`
}

// PostUserResponse defines model for PostUserResponse.
type PostUserResponse struct {
	User User `json:"user"`
}

// User defines model for User.
type User struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

// DeleteApiV1UserParams defines parameters for DeleteApiV1User.
type DeleteApiV1UserParams struct {
	Id string `form:"id" json:"id"`
}

// GetApiV1UserParams defines parameters for GetApiV1User.
type GetApiV1UserParams struct {
	Id string `form:"id" json:"id"`
}

// PatchApiV1UserParams defines parameters for PatchApiV1User.
type PatchApiV1UserParams struct {
	Id string `form:"id" json:"id"`
}

// PatchApiV1UserJSONRequestBody defines body for PatchApiV1User for application/json ContentType.
type PatchApiV1UserJSONRequestBody = PatchUserRequest

// PostApiV1UserJSONRequestBody defines body for PostApiV1User for application/json ContentType.
type PostApiV1UserJSONRequestBody = PostUserRequest
